[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "faster-whisper>=1.1.1",
    "pydub>=0.25.1",
    "pytube>=15.0.0",
    "youtube-transcript-api>=1.1.0",
]
